service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /api/overview
          method: post

plugins:
  - serverless-express

custom:
  express:
    app: ./index.app
